---
- name: "Destroy environment"
  amazon.aws.ec2_instance:
    key_name: "e2essh-{{runId}}"
    region: us-east-2
    security_group: e2e
    image_id: '{{nodeImage}}'
    tags:
      name: "e2e-{{nodeLabel}}-{{runId}}"
    exact_count: 0
    stage: absent
    filters:
      instance-id: "e2e-{{nodeLabel}}-{{runId}}"
  tags:
    - destroy
  async: 45
  poll: 0

- name: "Delete AWS keypair"
  ec2_key:
    region: us-east-2
    name: "e2essh-{{runId}}"
    state: absent
  tags:
    - destroy
  async: 45
  poll: 0
